### ISSUE TITLE
License terms?

### ISSUE THREAD

**Issue by tajmone** [SicroAtGit/PureBasic-CodeArchiv-Rebirth#3]
I've added to my **PureBASIC Archives** repo a reviewed link of this project:

https://github.com/tajmone/purebasic-archives/blob/master/README.md#purebasic-codearchiv-rebirth

I hope that my review is correct — if anything needs amending, just let me know.

I would like to know something more about **PureBasic-CodeArchiv-Rebirth**:

- What license will it be released under? Same as found on PureArea?
- Will it contain PureBASIC 5 codes only?
- Is the repo meant for building a website?
- What is the current state of the project?

Thanks

**Comment by SicroAtGit** [comment]
There isn't a problem. I say thank you for this ;-)

Currently, there is no license. The programmers of the codes are called in the code header.

Our goal is that all codes will always work with the latest Purebasic version.
The codes were collected from the forums. The forum threads, from where the codes are, are called in the code heads.

We are currently not planning a website. We see the representation on GitHub as sufficient for the beginning.

Currently we are collecting all useful codes of the German forum. The project has fallen asleep because the project manager has no time at the moment. That is why he handed over the project to me today. Now I am the only person to lead the project. The others are not really active, but have only added one, two codes, and then nothing more. In the next time I will work on the project again and add more codes.

You showed me that there is still interest in this project. Good to hear.

**Comment by tajmone** [comment]
Sounds great! 

>The project has fallen asleep because the project manager has no time at the moment. That is why he handed over the project to me today. 

I guess time is the number one issue for all of us — spare time comes and goes, but mostly is a rare commodity at best. But that's fine, the great thing about collaborative projects is the possibility of handing them over to others when we can no longer keep them alive.

>You showed me that there is still interest in this project. Good to hear.

Yes, indeed. I also experience problems with time, but I believe than in the long terms similar projects will managed to grow and survive.

Let's keep in touch about our projects developement. I'll do my best to integrate our resources, cross-reference them and follow up thei growth. Feel free to integrate anything that you see fit from the PB Archives.

I'm thinking of taking advantage of GitHub's Pages and Wiki, and to associate a website and a Wiki to the PB Archives. If you'd like to join in just let me know.

Keep up the good work!

**Comment by SicroAtGit** [comment]
All codes have been licensed since the recent rebuild.

No license for the whole project was added, because each code is independent and has its own copyright holders. This allows you to add any code with any license without creating a license conflict. But if the added code includes already existing codes from the code archive, the rules of the license of the included codes have of course to be observed to avoid a license conflict.

**Comment by tajmone** [comment]
> All codes have been licensed since the recent rebuild.

This is great news @SicroAtGit !

> No license for the whole project was added, because each code is independent and has its own copyright holders. This allows you to add any code with any license without creating a license conflict.

This makes sense, and doesn't implicitly bind contributions to any default license of the project.

Lately I've been sidetracked by other works, and the PureBASIC Archives revamp has alted for a few monthes — still some work to do before it gets published. But I'm planning to start working on it again very soon, and now that this repo has all licenses I'll be looking into contributing to this project, as well as working out a way to bridge its contents into the upcoming new version of PB-Archives.
