### ISSUE TITLE
Add Donation Button

### ISSUE THREAD

**Issue by tajmone** [SicroAtGit/PureBasic-CodeArchiv-Rebirth#8]
@SicroAtGit,

could you please add a PayPal :credit_card: donation button to the project?

This is the only PureBasic project truely alive and offering good resources. At least, when supporters of the project can't find the time to contribute code/time they can at least donate to it — time, _time_! :hourglass_flowing_sand: it's always a good in shortage. I wish we all had more time to share.

- https://hc.weebly.com/hc/en-us/articles/205737658-Accept-Donations-with-PayPal
- https://mcahalane.com/how-to-create-a-great-paypal-donate-link/

The donation button is also a good way to measure the pulse of love :heartpulse: for the project. I mean, people can donate even just 5 euros, which is like treating a friend for a coffee :coffee:, but it still makes a difference, especially in terms of motivation (it also counters the bitterness of critiques :rage:, which usually come free, and plentyful :trollface:).

**Comment by SicroAtGit** [comment]
Maybe later, when the project has grown bigger and requires more of my free time.

In my opinion, the code authors should rather receive donations than me, who mostly only archives the codes.

**Comment by tajmone** [comment]
> Maybe later, when the project has grown bigger and requires more of my free time.

Why? the project is already the biggest collection of PB assets on the internet. Donations are just a way to show appreciation. Let's put it this way, if we accidentally met tomorrow in the street wouldn't we offer each other a coffee? Donations are like "virtual coffees", to compensate the fact that chances of face to face meetings are unlikely due to distance.


> In my opinion, the code authors should rather receive donations than me, who mostly only archives the codes.

That would be difficult but not impossible to achieve. There are ways to set that donations get distributed among different accounts, but you'd need all authors to agree to that and set their PayPal account accordingly.

**Comment by SicroAtGit** [comment]
> Let's put it this way, if we accidentally met tomorrow in the street wouldn't we offer each other a coffee?

Yes, sure. At the moment I have invested more free time into the project, but this could look different later and then I would probably pay you the coffee.

Many codes in the archive are not only from me, but also from many other programmers. So let's look at the situation from a different point of view: Would you still only offer me a coffee if you had all the code writers — who also spent a lot of free time writing the codes — in front of you and not just me?

Other open source projects have to pay money for web space and so on. These donations can cover the costs a bit.  So the donations don't just benefit the project owner, but everyone gets something out of it.

I have no money to pay for keeping the project alive -- at least not yet. At the moment, I also have no idea how I could use the donations so that everyone has added value to the project.

Maybe it would be ok if I put beside the donation button a note that the donations possibly only go to me. Then the donor knows about it and can decide for himself whether it is fair or not.
(https://opensource.stackexchange.com/questions/1600/donations-and-open-source-projects-with-multiple-contributors)

I will leave the issue open for a while and read opinions on the internet also from others.

**Comment by tajmone** [comment]
> Would you still only offer me a coffee if you had all the code writers — who also spent a lot of free time writing the codes — in front of you and not just me?

Well, if all the contributors (let's say 20 of them) happened to be in the same phisical location at once that would be quite an historical event and a great opportunity, so it would call for inviting everyone for a pizza.

The parallel still holds true, for the situation in the PB community is like if there have been many open invitations for meeting and having coffee/pizza, but then most people don't turn up — ie. right now there aren't any ongoing multi-collaborators projects that I'm aware of.

Another solution then could be to create a __Contributors__ page where you:

- List alphabetically all authors of the code in the project, providing a link to their website or GitHub profile (if any) and mention their code present in the project.
- If any author has a donation link on his website, add it next to his name in the list.
- Place project mantainers on top of the list, again with links to website and/or donation. Project maintainers could have a shared donation button that automatically shares any donation amongst them, for they constitute a category on their own.

This way users get a chance to see who contribute what (to the PB community in general) and who's working at keeping alive the project, and gets a chance to make a donation to any author he wishes. Obviously, you should make it clear that any author could add/ask for a specific website/profile link and provide a donation link too.

This would be fair and transparent because you'd be offering visitors a fair resume of who's who and who's done what, and the choice to donate to whomever he/she feels. Maybe someone used a specific code for his work project and wishes to give back to its author via donation, and since he/she found the code in this project he might expect to find a reference/donation link here too.

Even if initially there was only your donation button in this page, it would still be fair because all authors would have a chance to see their button there too, and everyone's role/contribution would be clear.

When tracing back authors of some open source PB code, and visited their personal website, I did find some donation buttons in their resources download page.

Bare in mind that if donations were to take off, you could then think of using donations to promote PB projects, e.g. to outsource programmers to write library bindings/wrappers, etc. The project could become a reference point to discuss and promote such projects.


But the main issue here is the one mentioned above, i.e. that it's hard to get everyone to meet for a "virtual coffee" — beside sharing on the PB Forum, there are many scattered isolated projects but no active collaborative projects. In my view what is important about the donation button is that it shows a certain degree of commitment to keeping alive the project.

**Comment by SicroAtGit** [comment]
I recently read this reasoning of why donations are not accepted:

> I don't want the administrative workload coming with donations. I don't want the project to become in need of funding in any way: no dedicated home page + no forum = no cost = no need for funding. I want to be free to move onto something else if ever I get tired working on these projects (no donations  = no expectations).
>
> (Source: https://github.com/gorhill/uBlock/wiki/Why-don%27t-you-accept-donations%3F)

I agree with that reasoning.

Money is not helping the project at the moment.

It makes much more sense to provide further codes for the CodeArchiv or to check already contained codes for errors, to improve them, to extend them or to document them. 

It is also helpful to make the CodeArchiv more popular. So that new contributors join the project and make the future of the project more secure.

**Comment by SicroAtGit** [comment]
When the time comes, I'll get back to it. Thank you very much for your thoughts about this topic.
